### PR TITLE
 * [#247] Add optional flag to forcibly disconnect without sending…

### PR DESCRIPTION
**Pull request by mattrpav**
Please make sure that the following boxes are checked before submitting your Pull Request, thank you!
- [x] You have signed the [Eclipse CLA](http://www.eclipse.org/legal/CLA.php)
- [x] All of your commits have been signed-off with the correct email address (The same one that you used to sign the CLA)
- [x] If This PR fixes an issue, that you reference the issue below. OR if this is a new issue that you are fixing straight away that you add some Description about the bug and how this will fix it.
- [ ] If this is new functionality, You have added the appropriate Unit tests.

… the disconnect packet to trigger LW message.

ref: https://github.com/eclipse/paho.mqtt.java/issues/247
original bug ref: https://bugs.eclipse.org/bugs/show_bug.cgi?id=499935

Signed-off-by: Matt Pavlovich mattrpav@gmail.com

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=4999935

**Comment by mattrpav** [comment]
This feature closes a gap when compared to the FuseSource MQTT client where there is the ability to close a connection without sending the DISCONNECT packet. This allows for testing and simulating the triggering of the LastWill message using the Paho Java MQTT client.

**Comment by jpwsutton** [comment]
@mattrpav Thanks for this PR, this seems like a good idea to me and would be quite handy with testing LastWill functionality.

In order for us to accept this PR, you will need to sign the Eclipse ECA, please see the FAQ here: https://www.eclipse.org/legal/ecafaq.php

**Comment by mattrpav** [comment]
@jpwsutton my Eclipse account is under 'mattrpav@gmail.com' and my preferences are showing me that the ECA confirmed. Let me know if I missed something.

Thanks,
Matt

**Comment by jpwsutton** [comment]
Looks like the ECA check got caught looking at localhost for some reason, thanks for checking.

**Comment by mattrpav** [comment]
Thanks!

**Pull request merged**
