### PR TITLE
Use random UUID for 16-byte key in handshake request

### PR DESCRIPTION
**Pull request by miketran78727**
Please make sure that the following boxes are checked before submitting your Pull Request, thank you!
- [ x ] You have signed the [Eclipse CLA](http://www.eclipse.org/legal/CLA.php)
- [ x ] All of your commits have been signed-off with the correct email address (The same one that you used to sign the CLA)
- [ x ] If This PR fixes an issue, that you reference the issue below. OR if this is a new issue that you are fixing straight away that you add some Description about the bug and how this will fix it.
- [ ] If this is new functionality, You have added the appropriate Unit tests.

This is a proposed fix for issue https://github.com/eclipse/paho.mqtt.java/issues/234

I tested the fix against MessageSight broker messagesight.demo.ibm.com and ran existing jUnit tests in my local build.

### CODE REVIEW

**Comment by jpwsutton** [comment]
Thanks mike, this looks good to me. We need to put this into develop, would you mind re-creating the PR with develop as the target please? Once you've done that I'll merge it straight away.

**Comment by miketran78727** [comment]
My bad, I will regenerate the PR

**Comment by miketran78727** [comment]
Hi James, I re-based the target to develop branch. Is this pull request OK now or it is must be deleted and recreated?

**Comment by jpwsutton** [comment]
@miketran78727 One other small thing I've remembered, java.util.UUID is unavailable in java 1.4.2. I've kicked off a discussion on the mailing list about dropping support for 1.4.2 as I believe it's about time we moved onto a more modern JDK. As such, I've manually merged your change into the new java-1.6+ branch here: https://github.com/eclipse/paho.mqtt.java/commits/java-1.6%2B

The plan is that once the 1.3.0 release goes out in November, we can drop support for 1.4.2 and start making changes for future releases that don't limit us to older versions of Java. Until then, we can use the java-1.6+ (or maybe 1.7+) branch to store these commits.

**Pull request closed without merging**
