### PR TITLE
Issue #352 - Support message buffering before initial connect

### PR DESCRIPTION
**Pull request by matsukaz**
This change will enable offline buffering even if initial connection has never been established yet.

Please make sure that the following boxes are checked before submitting your Pull Request, thank you!

- [x] You have signed the [Eclipse ECA](https://wiki.eclipse.org/ECA)
- [x] All of your commits have been signed-off with the correct email address (The same one that you used to sign the CLA)
- [x] If This PR fixes an issue, that you reference the issue below. OR if this is a new issue that you are fixing straight away that you add some Description about the bug and how this will fix it.
- [x] If this is new functionality, You have added the appropriate Unit tests.

### CODE REVIEW

**Comment by matsukaz** [comment]
I'm currently fixing some problem, so please wait for a while to check this pr. sorry.

**Comment by matsukaz** [comment]
There is a serious problem about connection on latest develop branch as I mentioned on #355 
It should be fixed before considering about this pr, because the problem might affect it's feature.

**Comment by maartenl945** [comment]
Merged your changes on the 1.1.1 release and built it ourselves. Seems to work fine. Thanks a lot!

**Comment by MacroChip** [comment]
@matsukaz Thank you for implementing this. Unfortunately, I am having trouble getting this to work. What is required to get it working? I am setting DisconnectedBufferOptions on my client and sending messages before the client is connected, but the messages are not being sent once the connection is established.

**Comment by matsukaz** [comment]
@MacroChip Hi, which branch position are you using? I couldn't wait till next release for my app, so I'm using paho.mqtt.java just after this commit on my local repository as follows. Not the latest branch.
https://github.com/matsukaz/paho.mqtt.java/commits/matsukaz_develop

If you are using paho.mqtt.java through paho.mqtt.android, you might need to include the follow pr also.
https://github.com/eclipse/paho.mqtt.android/pull/198

My app uses the following branch that includes the above pr.
https://github.com/matsukaz/paho.mqtt.android/tree/matsukaz_develop

I don't know if this feature works on the latest paho.mqtt.android branch, because it doesn't include my pr yet...

**Comment by MacroChip** [comment]
@matsukaz Thank you for your response. I am using mqttv3:1.2.0 from maven central. If you run `git tag --contains fe8be8e` your commit is in there. That would lead me to believe that your code is in that release.

**Comment by ceefour** [comment]
@MacroChip I think if you're using Android, @matsukaz is correct, https://github.com/eclipse/paho.mqtt.android/pull/198 is required which is not yet merged :(
I also have the same issue.

**Comment by MacroChip** [comment]
@ceefour Understood. My testing did not involve Android so it is still unclear if this code is working as expected or if I made a mistake configuring/testing it.

**Comment by matsukaz** [comment]
@MacroChip In my case, I'm using `DisconnectedBufferOptions` with `setBufferEnabled` option set to true as follows. Did you set `setBufferEnabled` option to true?

```
            DisconnectedBufferOptions bufOpts = new DisconnectedBufferOptions();
            bufOpts.setBufferEnabled(true);
            bufOpts.setBufferSize(1024);
            this.mqttAndroidClient.setBufferOpts(bufOpts);
```

**Pull request merged**
