### PR TITLE
Next test for IP check

### PR DESCRIPTION
**Pull request by hendrikebbers**
Just a IP check PR

### CODE REVIEW

**Comment by hendrikebbers** [comment]
mmmh, 'ECA VALIDATION TOOL' on eclipse.org says:
There is a valid ECA on file for hxxxxxxx.exxxxx@web.de.

No idea what to do now....

**Comment by hendrikebbers** [comment]
bildschirmfoto 2019-01-15 um 14 58 20

**Comment by icraggs** [comment]
Hi Hendrik.  You have to use the Git --signoff option on your commits.  This is different from gpg signing.    The Eclipse doc says:

_Non-committers must sign-off the commit, indicating that they aware of the terms by which the contribution has been provided to the project, using the same email address as used in the author field._

It does seem to me to be a bit of duplication seeing as you've already signed the ECA, but those are the rules.  The CONTRIBUTING.md file does mention this, maybe it could be clearer?

**Comment by icraggs** [comment]
As the other PR has worked, I assume I can close this one now.

**Pull request closed without merging**
