### PR TITLE
SocketTimeoutException should not cause websockets to disconnect

### PR DESCRIPTION
**Pull request by kandrej**
Signed-off-by: Andrej Krota <andrej.krota@gmail.com>

Please make sure that the following boxes are checked before submitting your Pull Request, thank you!

- [*] This change is against the develop branch, **not** master.
- [*] You have signed the [Eclipse ECA](https://wiki.eclipse.org/ECA)
- [*] All of your commits have been signed-off with the correct email address (The same one that you used to sign the CLA) _Hint: use the -s argument when committing_.
- [*] If This PR fixes an issue, that you reference the issue below. OR if this is a new issue that you are fixing straight away that you add some Description about the bug and how this will fix it.
- [*] If this is new functionality, You have added the appropriate Unit tests.

### CODE REVIEW

**Comment by MMaiero** [comment]
The changes are working for me. Thank you for the PR!

**Comment by Christoph15072019** [comment]
Hi, 

I investigated this issue without knowledge of this pull requests. What I recognized was:

- WebSocketReceiver: the receiver thread doesn't check if the input socket has available data. The constructor of WebSocketFrame is called always.
- on my system input.available() always returned 0. I am not sure if .available() really returns the amount of data ready to read. don't know exactly what the isReceiving() does, but I think it is never set to true.
- in case the constructor of WebSocketFrame is called without available data, byte firstByte = (byte) input.read(); throws a SocketTimeoutException
- this exception results in stopping the receiver thread, closing the socket.

I did some changes and now it is working on my side. Are you interested in the updated source files?

**Comment by kandrej** [comment]
Yes, please. 
Clone the project and commit your changes to your own repository.

**Comment by Christoph15072019** [comment]
have put it to https://github.com/Christoph15072019/paho.mqtt.java.websocketFix

**Comment by timtay-microsoft** [comment]
Since Christoph added his fixes to a non-forked repository, I went ahead and created a forked repository that will be easier to pull in that has his fixes here: https://github.com/timtay-microsoft/paho.mqtt.java/tree/websocketFix

**Pull request merged**
