### PR TITLE
Refactor NetworkModule creation; support custom protocols/schemes

### PR DESCRIPTION
**Pull request by Bisk1**
- [x] You have signed the [Eclipse ECA](https://wiki.eclipse.org/ECA)
- [x] All of your commits have been signed-off with the correct email address (The same one that you used to sign the CLA)
- [x] If This PR fixes an issue, that you reference the issue below. OR if this is a new issue that you are fixing straight away that you add some Description about the bug and how this will fix it.
- [x] If this is new functionality, You have added the appropriate Unit tests.'
Implements #486
Creating network modules is now split into protocol-specific classes
Custom protocol-specific implementations can be added
Removed dead code

### CODE REVIEW

**Comment by Bisk1** [comment]
What is the problem with my sign-off?

**Comment by mscheibler** [comment]
My PullRequest [Network module SPI](https://github.com/eclipse/paho.mqtt.java/pull/440) is basically the same topic. It would allow to add custom protocols/schemes by implementing them as Java SPI and adding them to the classpath.
Maybe we could join our efforts

**Comment by Bisk1** [comment]
@mscheibler very well, I haven't seen your PR. Closing mine then.

**Comment by mscheibler** [comment]
I hope that mine PR gets merged in the foreseeable future. I updated it a few times already, but after the initial contect there was no resopse from the project owner. Maybe another voice could help.

**Pull request closed without merging**
