### PR TITLE
Fix incorrectly calculated reconnect delay

### PR DESCRIPTION
**Pull request by mingdong**
Please make sure that the following boxes are checked before submitting your Pull Request, thank you!
- [x] You have signed the [Eclipse CLA](http://www.eclipse.org/legal/CLA.php)
- [x] All of your commits have been signed-off with the correct email address (The same one that you used to sign the CLA)
- [x] If This PR fixes an issue, that you reference the issue below. OR if this is a new issue that you are fixing straight away that you add some Description about the bug and how this will fix it.
- [x] If this is new functionality, You have added the appropriate Unit tests.

Signed-off-by: mingdong mingdong@tellybean.com

### CODE REVIEW

**Comment by jpwsutton** [comment]
Hi @mingdong, I'm not sure why we would want to add 8 seconds onto the automatic reconnect delay? What's the point of this PR?

**Comment by mingdong** [comment]
Original logic is incorrect, it will be always not equal to 120000, then delay(1000) is always multiple by 2 no ending. 128000 just a convenient value to cope with that.

**Comment by ghost** [comment]
As Mingdong pointed out, the reconnection logic is not working properly. The initial delay is 1 second and then it gets doubled for every retry: 1,2,4,8,16,32,64,128  
The `if` will never work: `reconnectDelay != 120000` since the value goes from 64000 to 128000.
So the delay keeps increasing forever. Clearly, this was not the intended behavior.
I checked the tests and I don't think they failed because of this change.
Please let us know if we need to do something else for this pull request to be accepted.

**Comment by jpwsutton** [comment]
Doh! Good point! We froze our IP log for the Neon Release a few weeks back so I wont be able to merge in this PR, as this is a small change I'll pop it in manually now.

**Comment by ghost** [comment]
Thank you @jpwsutton!

**Pull request closed without merging**
