### PR TITLE
Fix #634: NPE when default file persistence tries to restore persiste…

### LINKED ISSUE #634: NullPointerException on MqttPersistentData.<init>
- [x] Bug exists Release Version 1.2.0 ( Master Branch)
- [x] Bug exists in MQTTv3 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

I experience a NullPointerException here:
https://github.com/eclipse/paho.mqtt.java/blob/f30e10b26320d63649904d163dced2b4f4330c97/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/internal/MqttPersistentData.java#L63

if called from here (argument `payload` is null):
https://github.com/eclipse/paho.mqtt.java/blob/5af7b53499e7dbe45b7227b3d41fc870089c0033/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/persist/MqttDefaultFilePersistence.java#L219

There should be a null check in MqttPersistentData constructor.

StackTrace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object byte[].clone()' on a null object reference
     at org.eclipse.paho.client.mqttv3.internal.MqttPersistentData.<init>(MqttPersistentData.java:63)
     at org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence.get(MqttDefaultFilePersistence.java:219)
     at org.eclipse.paho.client.mqttv3.internal.ClientState.restoreState(ClientState.java:342)
     at org.eclipse.paho.client.mqttv3.internal.ClientState.<init>(ClientState.java:172)
     at org.eclipse.paho.client.mqttv3.internal.ClientComms.<init>(ClientComms.java:108)
     at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:470)
     at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:320)
     at org.eclipse.paho.android.service.MqttConnection.connect(MqttConnection.java:289)
     at org.eclipse.paho.android.service.MqttService.connect(MqttService.java:329)
     at org.eclipse.paho.android.service.MqttAndroidClient.doConnect(MqttAndroidClient.java:467)
     at org.eclipse.paho.android.service.MqttAndroidClient.access$200(MqttAndroidClient.java:76)
     at org.eclipse.paho.android.service.MqttAndroidClient$MyServiceConnection.onServiceConnected(MqttAndroidClient.java:115)
     at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1223)
     at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1240)
     at android.os.Handler.handleCallback(Handler.java:739)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:148)
```

### PR DESCRIPTION
**Pull request by msqr**
…d data using only header data array.

Signed-off-by: Matt Magoffin <matt@solarnetwork.net>

Please make sure that the following boxes are checked before submitting your Pull Request, thank you!

- [x] This change is against the develop branch, **not** master.
- [x] You have signed the [Eclipse ECA](https://wiki.eclipse.org/ECA)
- [x] All of your commits have been signed-off with the correct email address (The same one that you used to sign the CLA) _Hint: use the -s argument when committing_.
- [x] If This PR fixes an issue, that you reference the issue below. OR if this is a new issue that you are fixing straight away that you add some Description about the bug and how this will fix it.
- [x] If this is new functionality, You have added the appropriate Unit tests.

Fixes #634.

### CODE REVIEW

**Comment by ogis-yamazaki** [comment]
@msqr
Currently, will skip the travis mqttv5 test  by commit e92138e096ee407f513dd35a990fa046713cfaad.

Try pull requesting again.

**Comment by msqr** [comment]
@ogis-yamazaki I updated my PR to the latest in `develop` but still the CI build failed, from some other test that looks unrelated to my change.

**Comment by jensli** [comment]
The build failure of the patch probably because of some environmental issue. It should be resolved by simply re-running the build.

```
Failed tests: 
  SendReceiveAsyncTest.testConnectTimeout:663 expected:<false> but was:<true>
```

**Comment by rdasgupt** [comment]
The fix looks good to me however the travis build failed for this PR. I restarted travis build and it failed again. Some of the tests are failing. I think the tests failures are not due to this PR.

I will pull this PR in my test repository and try to build with the latest develop branch. If my test build succeeds, I will merge this PR.

**Comment by rdasgupt** [comment]
My test build with the latest develop branch and this PR passed all checks. I am merging this PR.

**Comment by rdasgupt** [comment]
develop build with this PR passed:
https://travis-ci.org/github/eclipse/paho.mqtt.java/builds/671724738

**Pull request merged**
