### PR TITLE
Fix proxy usage for ssl/wss connections

### PR DESCRIPTION
**Pull request by a-zink**
- [x] This change is against the develop branch, **not** master.
- [x] You have signed the [Eclipse ECA](https://wiki.eclipse.org/ECA)
- [x] All of your commits have been signed-off with the correct email address (The same one that you used to sign the CLA) _Hint: use the -s argument when committing_.
- [x] If This PR fixes an issue, that you reference the issue below. OR if this is a new issue that you are fixing straight away that you add some Description about the bug and how this will fix it.
- [x] If this is new functionality, You have added the appropriate Unit tests.

Fixes issue https://github.com/eclipse/paho.mqtt.java/issues/573
Makes pull request https://github.com/eclipse/paho.mqtt.java/pull/456 obsolete

### CODE REVIEW

**Comment by shirou** [comment]
I am facing same problem. Any schedule on test and merge this PR?

**Comment by a-zink** [comment]
Maybe @jpwsutton can give a short comment?

**Comment by icraggs** [comment]
Thanks for the contribution.  Sorry for the delay.  Do you have a test or usage which shows how this fixes the issue?  As I'm stretched at the moment, I'll get to it as soon as I can.

**Comment by icraggs** [comment]
I've been looking at this today, and unfortunately it doesn't work.  The build run on this PR hasn't run the tests which is why this didn't show up.  

The problem is that the call

socket = ((SSLSocketFactory)factory).createSocket(socket, host, port, true);

is operating on a socket which is created by an SSLSocketFactory already.

**Comment by a-zink** [comment]
I'll have another look as soon as possible. But I actually don't see the problem. Yes, the underlying Socket might already be created using SSLSocketFactory, but it was created using factory.createSocket(), which delegates to the inherited SocketFactory.

**Comment by icraggs** [comment]
I have a fix which I'm testing, which is basically reverting the code to as it was, with some additional changes to make sure SNI works.  I expect to commit it early next week, but I could do with someone trying it out while I figure out how to add a proxy test to the CI test suite.

**Comment by icraggs** [comment]
I've made a change which I think fixes issue #573.  If you get the chance to try it, then I would like to know if it works for you.  Thanks!

**Pull request closed without merging**
